// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhebftoumkaazzjvntfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWJmdG91bWthYXp6anZudGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODM1NjYsImV4cCI6MjA3MTc1OTU2Nn0.yTVwvgQvzBt4uq9Xw4vjeFXLulr5oj5ETeaMP6wY2Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});